### PR TITLE
[JENKINS-66197] Touch a specific file instead of the JENKINS_HOME directory

### PR DESCRIPTION
**Pull request by PierreBtz**
### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by oliverlockwood** [comment]
I have tested this on a Jenkins installation affected by https://issues.jenkins.io/browse/JENKINS-66197, and the fix works a treat.  Thank you.

**Comment by PierreBtz** [comment]
@oliverlockwood Thanks for taking the time to test, release was just performed, it should be visible in the Update Center in 2 to 3 hours: https://github.com/jenkinsci/cloudbees-disk-usage-simple-plugin/releases/tag/203.v3f46a_7462b_1a_

**Comment by oliverlockwood** [comment]
@PierreBtz you're welcome.
I've now upgraded to yesterday's release, and can confirm that (unsurprisingly!) the issue remains fixed.

Thanks again for resolving this.

**Comment by PierreBtz** [comment]
Great, thanks for the feedback!

**Pull request merged**
