### PR TITLE
Use new table style

### PR DESCRIPTION
**Pull request by farodin91**
image
image

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by farodin91** [comment]
@aheritier Would you like to review?

**Review by aheritier — APPROVED** [review]
completely miss this notification @farodin91 
Thanks a lot for this contribution
it looks good to me

**Comment by farodin91** [comment]
@aheritier I fixed by updating to a new version.
image

**Comment by farodin91** [comment]
@aheritier What do you think of the version without border?

**Comment by timja** [comment]
That looks better although now it’s the large empty space which looks weird which is probably a pre existing problem.

**Comment by timja** [comment]
Between item name and disk space

**Comment by farodin91** [comment]
image
 Current version

**Comment by timja** [comment]
If you wanted to try improve it would be good to get a few more jobs of differing length and you could either play with bootstrap columns or custom css.

but either way this is an improvement over what was there before 😄

**Comment by farodin91** [comment]
@timja If I'm correct Item name column will take all that is available. So it should look good with long names.

**Pull request merged**
